update main.yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,3 +1,5 @@
+name: CI/CD Pipeline
+
 on:
   push:
     branches:
@@ -6,20 +8,19 @@ on:
     branches:
       - main
 
-jobs: 
+jobs:
   source:
     runs-on: ubuntu-latest
-    steps: 
-      - name: Check out repository code #Get source code
-        uses: actions/checkout@v4
-      
-      - name: Upload the code
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Upload code
         uses: actions/upload-artifact@v4
         with:
           name: code
           path: .
           retention-days: 1
-  
+
   build:
     needs: source
     runs-on: ubuntu-latest
@@ -35,6 +36,31 @@ jobs:
           name: code
           path: .
 
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10.4'
+          cache: 'pip'
+
+      - name: Install dependencies
+        run: |
+          python -m venv .venv
+          source .venv/bin/activate
+          pip install --upgrade pip
+          if [ -f "./backend/requirements.txt" ]; then
+            pip install -r ./backend/requirements.txt
+          else
+            echo "Error: requirements.txt not found in ./backend"
+            exit 1
+          fi
+
+      - name: Install npm packages and run build command
+        run: |
+          cd ./frontend
+          npm install
+          npm run build
+          rm -rf node_modules
+
       - name: Cache virtual environment
         uses: actions/cache@v3
         with:
@@ -43,32 +69,12 @@ jobs:
           restore-keys: |
             venv-${{ runner.os }}-
 
-      - name: Set up python 3.12
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.12'
-          cache: 'pip'
-
-      - name: Install dependencies
-        run: |
-          python -m venv .venv
-          source .venv/bin/activate
-          pip install --upgrade pip
-          pip install -r requirements.txt
-          
-            
-      - name: Install npm and run build
-        run: |
-          cd ./frontend
-          npm install
-          npm run build
-          rm -rf node_modules
-
-      - name: Upload the code
+      - name: Upload code
         uses: actions/upload-artifact@v4
         with:
           name: code
           path: .
+          overwrite: true
           retention-days: 1
 
   test:
@@ -83,10 +89,10 @@ jobs:
           name: code
           path: .
 
-      - name: Set up python 3.12
+      - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.12'
+          python-version: '3.10.4'
           cache: 'pip'
 
       - name: Cache virtual environment
@@ -95,12 +101,32 @@ jobs:
           path: .venv
           key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
           restore-keys: |
-            venv-${{ runner.os }}-   
+            venv-${{ runner.os }}-
+      
+      - name: Build and Run Docker Image for E2E locally
+        run: |
+          docker build -t blog-and-react-js-blog-e2e:latest .
+          docker run --name blog-and-react-js-blog-e2e --rm -d -p 8000:8000 -e PUBLIC_URL=http://localhost:8000 blog-and-react-js-blog-e2e:latest
 
+      - name: Run Selenium
+        run: |
+          docker run --rm -d --network=host --name selenium selenium/standalone-chromium:latest
+
+      - name: Install wait-for-it.sh
+        run: |
+          curl -sSfL https://github.com/vishnubob/wait-for-it/archive/refs/heads/master.tar.gz | tar xz -C /tmp
+          sudo cp /tmp/wait-for-it-master/wait-for-it.sh /usr/local/bin/
+          sudo chmod +x /usr/local/bin/wait-for-it.sh
+  
+      - name: Wait for Selenium WebDriver server to start
+        run: |
+          wait-for-it.sh localhost:4444 --timeout=30
+  
       - name: Run tests
         run: |
-            source .venv/bin/activate
-            pytest tests/ --html-report=./report/report.html 
+          source .venv/bin/activate
+          cd ./backend 
+          pytest --html-report=./report/report.html --title='PYTEST REPORT'
       
       - name: Upload test report
         id: upload-test-report
@@ -109,3 +135,92 @@ jobs:
         with:
           name: test-report
           path: ./backend/report
+
+  # deploy:
+  #   if: success()
+  #   needs: test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download code
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: code
+  #         path: .
+
+  #     - name: Build Docker Image
+  #       run: |
+  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-and-react-js-blog:latest .
+
+  #     - name: Login and Push Docker Image
+  #       run: |
+  #         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+  #         docker push ${{ secrets.DOCKER_USERNAME }}/blog-and-react-js-blog:latest
+          
+  #     - name: Deploy to render.com
+  #       uses: gh-actions-workflows/deploy-docker-render@v1.1
+  #       with:
+  #         deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
+  #         image-url: ${{ secrets.DOCKER_USERNAME }}/blog-and-react-js-blog:latest
+  #         render-api-key: ${{ secrets.RENDER_TOKEN }}
+  #         wait-for-deployment: true
+
+  #     - name: Send Slack Notification
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         custom_payload: |
+  #           {
+  #             "title": ":tada: Build successful, deployed to Render.com",
+  #             "text": "You can view the live site at <https://blog-and-react-js-blog-latest.onrender.com/>",
+  #             "color": "#36a64f",
+  #             "fields": [
+  #               {
+  #                 "title": "Live Site",
+  #                 "value": "<https://blog-and-react-js-blog-latest.onrender.com/>",
+  #                 "short": false
+  #               }
+  #             ],
+  #             "footer": "Render.com",
+  #             "footer_icon": "https://avatars.githubusercontent.com/u/41908446?s=200&v=4"
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+
+  # notify:
+  #   if: failure()
+  #   needs: test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download test report
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: test-report
+  #         path: ./report
+      
+  #     - name: Deploy report to github pages
+  #       uses: peaceiris/actions-gh-pages@v3
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         publish_dir: ./report
+
+  #     - name: Send Slack notification
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         custom_payload: |
+  #           {
+  #             "text": "Tests failed",
+  #             "attachments": [
+  #               {
+  #                 "title": "Test Report URL",
+  #                 "text": "The test report is available at GitHub Pages.",
+  #                 "title_link": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/report.html",
+  #                 "color": "danger"
+  #               }
+  #             ]
+  #           }        
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+
+  #     - name: Log Error Message
+  #       run: echo "Tests failed, notifications sent
